// Code generated by MockGen. DO NOT EDIT.
// Source: session.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	model "gophkeeper/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// AddSession mocks base method.
func (m *MockSessionService) AddSession(ctx context.Context, tokenAuth model.TokenAuth) (model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSession", ctx, tokenAuth)
	ret0, _ := ret[0].(model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSession indicates an expected call of AddSession.
func (mr *MockSessionServiceMockRecorder) AddSession(ctx, tokenAuth interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSession", reflect.TypeOf((*MockSessionService)(nil).AddSession), ctx, tokenAuth)
}

// GetSession mocks base method.
func (m *MockSessionService) GetSession(ctx context.Context, code string) (model.TokenAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, code)
	ret0, _ := ret[0].(model.TokenAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionServiceMockRecorder) GetSession(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionService)(nil).GetSession), ctx, code)
}
