// Code generated by MockGen. DO NOT EDIT.
// Source: token.go

// Package middleware is a generated GoMock package.
package middleware

import (
	model "gophkeeper/internal/model"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenMiddleware is a mock of TokenMiddleware interface.
type MockTokenMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMiddlewareMockRecorder
}

// MockTokenMiddlewareMockRecorder is the mock recorder for MockTokenMiddleware.
type MockTokenMiddlewareMockRecorder struct {
	mock *MockTokenMiddleware
}

// NewMockTokenMiddleware creates a new mock instance.
func NewMockTokenMiddleware(ctrl *gomock.Controller) *MockTokenMiddleware {
	mock := &MockTokenMiddleware{ctrl: ctrl}
	mock.recorder = &MockTokenMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenMiddleware) EXPECT() *MockTokenMiddlewareMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockTokenMiddleware) CheckToken(arg0 http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", arg0)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockTokenMiddlewareMockRecorder) CheckToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockTokenMiddleware)(nil).CheckToken), arg0)
}

// GetUserRequest mocks base method.
func (m *MockTokenMiddleware) GetUserRequest(arg0 *http.Request) model.TokenAuth {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRequest", arg0)
	ret0, _ := ret[0].(model.TokenAuth)
	return ret0
}

// GetUserRequest indicates an expected call of GetUserRequest.
func (mr *MockTokenMiddlewareMockRecorder) GetUserRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRequest", reflect.TypeOf((*MockTokenMiddleware)(nil).GetUserRequest), arg0)
}
