// Code generated by MockGen. DO NOT EDIT.
// Source: card.go

// Package service is a generated GoMock package.
package service

import (
	model "gophkeeper/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCardService is a mock of CardService interface.
type MockCardService struct {
	ctrl     *gomock.Controller
	recorder *MockCardServiceMockRecorder
}

// MockCardServiceMockRecorder is the mock recorder for MockCardService.
type MockCardServiceMockRecorder struct {
	mock *MockCardService
}

// NewMockCardService creates a new mock instance.
func NewMockCardService(ctrl *gomock.Controller) *MockCardService {
	mock := &MockCardService{ctrl: ctrl}
	mock.recorder = &MockCardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardService) EXPECT() *MockCardServiceMockRecorder {
	return m.recorder
}

// AddCard mocks base method.
func (m *MockCardService) AddCard(arg0 model.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCard", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCard indicates an expected call of AddCard.
func (mr *MockCardServiceMockRecorder) AddCard(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCard", reflect.TypeOf((*MockCardService)(nil).AddCard), arg0)
}

// DeleteCard mocks base method.
func (m *MockCardService) DeleteCard(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCard", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCard indicates an expected call of DeleteCard.
func (mr *MockCardServiceMockRecorder) DeleteCard(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCard", reflect.TypeOf((*MockCardService)(nil).DeleteCard), arg0)
}

// GetCards mocks base method.
func (m *MockCardService) GetCards() ([]model.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCards")
	ret0, _ := ret[0].([]model.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCards indicates an expected call of GetCards.
func (mr *MockCardServiceMockRecorder) GetCards() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCards", reflect.TypeOf((*MockCardService)(nil).GetCards))
}

// SetMasterPass mocks base method.
func (m *MockCardService) SetMasterPass(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMasterPass", arg0)
}

// SetMasterPass indicates an expected call of SetMasterPass.
func (mr *MockCardServiceMockRecorder) SetMasterPass(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMasterPass", reflect.TypeOf((*MockCardService)(nil).SetMasterPass), arg0)
}

// UpdateCard mocks base method.
func (m *MockCardService) UpdateCard(arg0 model.Card) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCard", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCard indicates an expected call of UpdateCard.
func (mr *MockCardServiceMockRecorder) UpdateCard(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCard", reflect.TypeOf((*MockCardService)(nil).UpdateCard), arg0)
}
