// Code generated by MockGen. DO NOT EDIT.
// Source: sender.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSenderService is a mock of SenderService interface.
type MockSenderService struct {
	ctrl     *gomock.Controller
	recorder *MockSenderServiceMockRecorder
}

// MockSenderServiceMockRecorder is the mock recorder for MockSenderService.
type MockSenderServiceMockRecorder struct {
	mock *MockSenderService
}

// NewMockSenderService creates a new mock instance.
func NewMockSenderService(ctrl *gomock.Controller) *MockSenderService {
	mock := &MockSenderService{ctrl: ctrl}
	mock.recorder = &MockSenderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSenderService) EXPECT() *MockSenderServiceMockRecorder {
	return m.recorder
}

// SendDelete mocks base method.
func (m *MockSenderService) SendDelete(arg0 context.Context, arg1 string) ([]byte, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDelete", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendDelete indicates an expected call of SendDelete.
func (mr *MockSenderServiceMockRecorder) SendDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDelete", reflect.TypeOf((*MockSenderService)(nil).SendDelete), arg0, arg1)
}

// SendFile mocks base method.
func (m *MockSenderService) SendFile(arg0 context.Context, arg1 string, arg2 io.Reader, arg3 string) ([]byte, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFile", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendFile indicates an expected call of SendFile.
func (mr *MockSenderServiceMockRecorder) SendFile(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFile", reflect.TypeOf((*MockSenderService)(nil).SendFile), arg0, arg1, arg2, arg3)
}

// SendGet mocks base method.
func (m *MockSenderService) SendGet(arg0 context.Context, arg1 string) ([]byte, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendGet", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendGet indicates an expected call of SendGet.
func (mr *MockSenderServiceMockRecorder) SendGet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendGet", reflect.TypeOf((*MockSenderService)(nil).SendGet), arg0, arg1)
}

// SendGetFile mocks base method.
func (m *MockSenderService) SendGetFile(ctx context.Context, url string) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendGetFile", ctx, url)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendGetFile indicates an expected call of SendGetFile.
func (mr *MockSenderServiceMockRecorder) SendGetFile(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendGetFile", reflect.TypeOf((*MockSenderService)(nil).SendGetFile), ctx, url)
}

// SendPost mocks base method.
func (m *MockSenderService) SendPost(arg0 context.Context, arg1 string, arg2 []byte) ([]byte, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPost", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendPost indicates an expected call of SendPost.
func (mr *MockSenderServiceMockRecorder) SendPost(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPost", reflect.TypeOf((*MockSenderService)(nil).SendPost), arg0, arg1, arg2)
}

// SendPut mocks base method.
func (m *MockSenderService) SendPut(arg0 context.Context, arg1 string, arg2 []byte) ([]byte, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPut", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendPut indicates an expected call of SendPut.
func (mr *MockSenderServiceMockRecorder) SendPut(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPut", reflect.TypeOf((*MockSenderService)(nil).SendPut), arg0, arg1, arg2)
}

// SetToken mocks base method.
func (m *MockSenderService) SetToken(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToken", arg0)
}

// SetToken indicates an expected call of SetToken.
func (mr *MockSenderServiceMockRecorder) SetToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockSenderService)(nil).SetToken), arg0)
}
