// Code generated by MockGen. DO NOT EDIT.
// Source: credential.go

// Package service is a generated GoMock package.
package service

import (
	service "gophkeeper/internal/client/service"
	model "gophkeeper/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCredentialService is a mock of CredentialService interface.
type MockCredentialService struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialServiceMockRecorder
}

// MockCredentialServiceMockRecorder is the mock recorder for MockCredentialService.
type MockCredentialServiceMockRecorder struct {
	mock *MockCredentialService
}

// NewMockCredentialService creates a new mock instance.
func NewMockCredentialService(ctrl *gomock.Controller) *MockCredentialService {
	mock := &MockCredentialService{ctrl: ctrl}
	mock.recorder = &MockCredentialServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialService) EXPECT() *MockCredentialServiceMockRecorder {
	return m.recorder
}

// AddCredential mocks base method.
func (m *MockCredentialService) AddCredential(login, password, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCredential", login, password, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCredential indicates an expected call of AddCredential.
func (mr *MockCredentialServiceMockRecorder) AddCredential(login, password, masterPass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCredential", reflect.TypeOf((*MockCredentialService)(nil).AddCredential), login, password, masterPass)
}

// DeleteCredential mocks base method.
func (m *MockCredentialService) DeleteCredential(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredential", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredential indicates an expected call of DeleteCredential.
func (mr *MockCredentialServiceMockRecorder) DeleteCredential(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredential", reflect.TypeOf((*MockCredentialService)(nil).DeleteCredential), id)
}

// GetCredentials mocks base method.
func (m *MockCredentialService) GetCredentials(arg0 string) ([]model.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentials", arg0)
	ret0, _ := ret[0].([]model.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentials indicates an expected call of GetCredentials.
func (mr *MockCredentialServiceMockRecorder) GetCredentials(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentials", reflect.TypeOf((*MockCredentialService)(nil).GetCredentials), arg0)
}

// InitToken mocks base method.
func (m *MockCredentialService) InitToken(arg0 service.TokenService) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitToken", arg0)
}

// InitToken indicates an expected call of InitToken.
func (mr *MockCredentialServiceMockRecorder) InitToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitToken", reflect.TypeOf((*MockCredentialService)(nil).InitToken), arg0)
}

// UpdateCredential mocks base method.
func (m *MockCredentialService) UpdateCredential(login, password, masterPass, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredential", login, password, masterPass, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCredential indicates an expected call of UpdateCredential.
func (mr *MockCredentialServiceMockRecorder) UpdateCredential(login, password, masterPass, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredential", reflect.TypeOf((*MockCredentialService)(nil).UpdateCredential), login, password, masterPass, id)
}
