// Code generated by MockGen. DO NOT EDIT.
// Source: file.go

// Package service is a generated GoMock package.
package service

import (
	service "gophkeeper/internal/client/service"
	model "gophkeeper/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileService is a mock of FileService interface.
type MockFileService struct {
	ctrl     *gomock.Controller
	recorder *MockFileServiceMockRecorder
}

// MockFileServiceMockRecorder is the mock recorder for MockFileService.
type MockFileServiceMockRecorder struct {
	mock *MockFileService
}

// NewMockFileService creates a new mock instance.
func NewMockFileService(ctrl *gomock.Controller) *MockFileService {
	mock := &MockFileService{ctrl: ctrl}
	mock.recorder = &MockFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileService) EXPECT() *MockFileServiceMockRecorder {
	return m.recorder
}

// AddFile mocks base method.
func (m *MockFileService) AddFile(filePath, masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFile", filePath, masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFile indicates an expected call of AddFile.
func (mr *MockFileServiceMockRecorder) AddFile(filePath, masterPass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFile", reflect.TypeOf((*MockFileService)(nil).AddFile), filePath, masterPass)
}

// DeleteFile mocks base method.
func (m *MockFileService) DeleteFile(fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileServiceMockRecorder) DeleteFile(fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileService)(nil).DeleteFile), fileName)
}

// DownloadFile mocks base method.
func (m *MockFileService) DownloadFile(fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockFileServiceMockRecorder) DownloadFile(fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockFileService)(nil).DownloadFile), fileName)
}

// InitToken mocks base method.
func (m *MockFileService) InitToken(arg0 service.TokenService) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitToken", arg0)
}

// InitToken indicates an expected call of InitToken.
func (mr *MockFileServiceMockRecorder) InitToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitToken", reflect.TypeOf((*MockFileService)(nil).InitToken), arg0)
}

// ListFile mocks base method.
func (m *MockFileService) ListFile() ([]model.FileAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFile")
	ret0, _ := ret[0].([]model.FileAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFile indicates an expected call of ListFile.
func (mr *MockFileServiceMockRecorder) ListFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFile", reflect.TypeOf((*MockFileService)(nil).ListFile))
}
