// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package service is a generated GoMock package.
package service

import (
	service "gophkeeper/internal/client/service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// InitToken mocks base method.
func (m *MockUserService) InitToken(arg0 service.TokenService) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitToken", arg0)
}

// InitToken indicates an expected call of InitToken.
func (mr *MockUserServiceMockRecorder) InitToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitToken", reflect.TypeOf((*MockUserService)(nil).InitToken), arg0)
}

// Login mocks base method.
func (m *MockUserService) Login(login, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceMockRecorder) Login(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserService)(nil).Login), login, password)
}

// Master mocks base method.
func (m *MockUserService) Master(masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Master", masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// Master indicates an expected call of Master.
func (mr *MockUserServiceMockRecorder) Master(masterPass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Master", reflect.TypeOf((*MockUserService)(nil).Master), masterPass)
}

// Register mocks base method.
func (m *MockUserService) Register(login, password, masterPass string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", login, password, masterPass)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceMockRecorder) Register(login, password, masterPass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserService)(nil).Register), login, password, masterPass)
}

// MockUserMasterService is a mock of UserMasterService interface.
type MockUserMasterService struct {
	ctrl     *gomock.Controller
	recorder *MockUserMasterServiceMockRecorder
}

// MockUserMasterServiceMockRecorder is the mock recorder for MockUserMasterService.
type MockUserMasterServiceMockRecorder struct {
	mock *MockUserMasterService
}

// NewMockUserMasterService creates a new mock instance.
func NewMockUserMasterService(ctrl *gomock.Controller) *MockUserMasterService {
	mock := &MockUserMasterService{ctrl: ctrl}
	mock.recorder = &MockUserMasterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserMasterService) EXPECT() *MockUserMasterServiceMockRecorder {
	return m.recorder
}

// Master mocks base method.
func (m *MockUserMasterService) Master(masterPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Master", masterPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// Master indicates an expected call of Master.
func (mr *MockUserMasterServiceMockRecorder) Master(masterPass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Master", reflect.TypeOf((*MockUserMasterService)(nil).Master), masterPass)
}
