// Code generated by MockGen. DO NOT EDIT.
// Source: card.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	model "gophkeeper/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCardRepository is a mock of CardRepository interface.
type MockCardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCardRepositoryMockRecorder
}

// MockCardRepositoryMockRecorder is the mock recorder for MockCardRepository.
type MockCardRepositoryMockRecorder struct {
	mock *MockCardRepository
}

// NewMockCardRepository creates a new mock instance.
func NewMockCardRepository(ctrl *gomock.Controller) *MockCardRepository {
	mock := &MockCardRepository{ctrl: ctrl}
	mock.recorder = &MockCardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardRepository) EXPECT() *MockCardRepositoryMockRecorder {
	return m.recorder
}

// AddCard mocks base method.
func (m *MockCardRepository) AddCard(ctx context.Context, card model.CardAPI, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCard", ctx, card, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCard indicates an expected call of AddCard.
func (mr *MockCardRepositoryMockRecorder) AddCard(ctx, card, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCard", reflect.TypeOf((*MockCardRepository)(nil).AddCard), ctx, card, userID)
}

// DeleteCard mocks base method.
func (m *MockCardRepository) DeleteCard(ctx context.Context, id string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCard", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCard indicates an expected call of DeleteCard.
func (mr *MockCardRepositoryMockRecorder) DeleteCard(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCard", reflect.TypeOf((*MockCardRepository)(nil).DeleteCard), ctx, id, userID)
}

// GetCard mocks base method.
func (m *MockCardRepository) GetCard(ctx context.Context, id string, userID int) (model.CardAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCard", ctx, id, userID)
	ret0, _ := ret[0].(model.CardAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCard indicates an expected call of GetCard.
func (mr *MockCardRepositoryMockRecorder) GetCard(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCard", reflect.TypeOf((*MockCardRepository)(nil).GetCard), ctx, id, userID)
}

// GetCards mocks base method.
func (m *MockCardRepository) GetCards(ctx context.Context, userID int) ([]model.CardAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCards", ctx, userID)
	ret0, _ := ret[0].([]model.CardAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCards indicates an expected call of GetCards.
func (mr *MockCardRepositoryMockRecorder) GetCards(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCards", reflect.TypeOf((*MockCardRepository)(nil).GetCards), ctx, userID)
}

// UpdateCard mocks base method.
func (m *MockCardRepository) UpdateCard(ctx context.Context, card model.CardAPI, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCard", ctx, card, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCard indicates an expected call of UpdateCard.
func (mr *MockCardRepositoryMockRecorder) UpdateCard(ctx, card, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCard", reflect.TypeOf((*MockCardRepository)(nil).UpdateCard), ctx, card, userID)
}
