// Code generated by MockGen. DO NOT EDIT.
// Source: counter.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	model "gophkeeper/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockCounterRepository is a mock of CounterRepository interface.
type MockCounterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCounterRepositoryMockRecorder
}

// MockCounterRepositoryMockRecorder is the mock recorder for MockCounterRepository.
type MockCounterRepositoryMockRecorder struct {
	mock *MockCounterRepository
}

// NewMockCounterRepository creates a new mock instance.
func NewMockCounterRepository(ctrl *gomock.Controller) *MockCounterRepository {
	mock := &MockCounterRepository{ctrl: ctrl}
	mock.recorder = &MockCounterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounterRepository) EXPECT() *MockCounterRepositoryMockRecorder {
	return m.recorder
}

// GetCounter mocks base method.
func (m *MockCounterRepository) GetCounter(tx pgx.Tx, ctx context.Context, typeCounter model.TypeCounter, userID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", tx, ctx, typeCounter, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockCounterRepositoryMockRecorder) GetCounter(tx, ctx, typeCounter, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockCounterRepository)(nil).GetCounter), tx, ctx, typeCounter, userID)
}

// IncrementCounter mocks base method.
func (m *MockCounterRepository) IncrementCounter(tx pgx.Tx, ctx context.Context, typeCounter model.TypeCounter, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", tx, ctx, typeCounter, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockCounterRepositoryMockRecorder) IncrementCounter(tx, ctx, typeCounter, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockCounterRepository)(nil).IncrementCounter), tx, ctx, typeCounter, userID)
}
