// Code generated by MockGen. DO NOT EDIT.
// Source: credential.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	model "gophkeeper/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCredentialRepository is a mock of CredentialRepository interface.
type MockCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRepositoryMockRecorder
}

// MockCredentialRepositoryMockRecorder is the mock recorder for MockCredentialRepository.
type MockCredentialRepositoryMockRecorder struct {
	mock *MockCredentialRepository
}

// NewMockCredentialRepository creates a new mock instance.
func NewMockCredentialRepository(ctrl *gomock.Controller) *MockCredentialRepository {
	mock := &MockCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRepository) EXPECT() *MockCredentialRepositoryMockRecorder {
	return m.recorder
}

// AddCredential mocks base method.
func (m *MockCredentialRepository) AddCredential(ctx context.Context, credential model.CredentialAPI, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCredential", ctx, credential, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCredential indicates an expected call of AddCredential.
func (mr *MockCredentialRepositoryMockRecorder) AddCredential(ctx, credential, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCredential", reflect.TypeOf((*MockCredentialRepository)(nil).AddCredential), ctx, credential, userID)
}

// DeleteCredential mocks base method.
func (m *MockCredentialRepository) DeleteCredential(ctx context.Context, login string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCredential", ctx, login, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCredential indicates an expected call of DeleteCredential.
func (mr *MockCredentialRepositoryMockRecorder) DeleteCredential(ctx, login, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCredential", reflect.TypeOf((*MockCredentialRepository)(nil).DeleteCredential), ctx, login, userID)
}

// GetCredential mocks base method.
func (m *MockCredentialRepository) GetCredential(ctx context.Context, login string, userID int) (model.CredentialAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredential", ctx, login, userID)
	ret0, _ := ret[0].(model.CredentialAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredential indicates an expected call of GetCredential.
func (mr *MockCredentialRepositoryMockRecorder) GetCredential(ctx, login, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredential", reflect.TypeOf((*MockCredentialRepository)(nil).GetCredential), ctx, login, userID)
}

// GetCredentials mocks base method.
func (m *MockCredentialRepository) GetCredentials(ctx context.Context, userID int) ([]model.CredentialAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentials", ctx, userID)
	ret0, _ := ret[0].([]model.CredentialAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentials indicates an expected call of GetCredentials.
func (mr *MockCredentialRepositoryMockRecorder) GetCredentials(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentials", reflect.TypeOf((*MockCredentialRepository)(nil).GetCredentials), ctx, userID)
}

// UpdateCredential mocks base method.
func (m *MockCredentialRepository) UpdateCredential(ctx context.Context, credential model.CredentialAPI, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredential", ctx, credential, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCredential indicates an expected call of UpdateCredential.
func (mr *MockCredentialRepositoryMockRecorder) UpdateCredential(ctx, credential, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredential", reflect.TypeOf((*MockCredentialRepository)(nil).UpdateCredential), ctx, credential, userID)
}
