// Code generated by MockGen. DO NOT EDIT.
// Source: file.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	model "gophkeeper/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileRepository is a mock of FileRepository interface.
type MockFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepositoryMockRecorder
}

// MockFileRepositoryMockRecorder is the mock recorder for MockFileRepository.
type MockFileRepositoryMockRecorder struct {
	mock *MockFileRepository
}

// NewMockFileRepository creates a new mock instance.
func NewMockFileRepository(ctrl *gomock.Controller) *MockFileRepository {
	mock := &MockFileRepository{ctrl: ctrl}
	mock.recorder = &MockFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepository) EXPECT() *MockFileRepositoryMockRecorder {
	return m.recorder
}

// AddFile mocks base method.
func (m *MockFileRepository) AddFile(ctx context.Context, file model.FileAdd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFile", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFile indicates an expected call of AddFile.
func (mr *MockFileRepositoryMockRecorder) AddFile(ctx, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFile", reflect.TypeOf((*MockFileRepository)(nil).AddFile), ctx, file)
}

// DeleteAllBlocks mocks base method.
func (m *MockFileRepository) DeleteAllBlocks(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllBlocks", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllBlocks indicates an expected call of DeleteAllBlocks.
func (mr *MockFileRepositoryMockRecorder) DeleteAllBlocks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllBlocks", reflect.TypeOf((*MockFileRepository)(nil).DeleteAllBlocks), ctx)
}

// DeleteBlockFile mocks base method.
func (m *MockFileRepository) DeleteBlockFile(ctx context.Context, userID int, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlockFile", ctx, userID, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlockFile indicates an expected call of DeleteBlockFile.
func (mr *MockFileRepositoryMockRecorder) DeleteBlockFile(ctx, userID, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlockFile", reflect.TypeOf((*MockFileRepository)(nil).DeleteBlockFile), ctx, userID, fileName)
}

// DeleteFile mocks base method.
func (m *MockFileRepository) DeleteFile(ctx context.Context, userID int, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, userID, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileRepositoryMockRecorder) DeleteFile(ctx, userID, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileRepository)(nil).DeleteFile), ctx, userID, fileName)
}

// DownloadFile mocks base method.
func (m *MockFileRepository) DownloadFile(ctx context.Context, userID int, fileName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, userID, fileName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockFileRepositoryMockRecorder) DownloadFile(ctx, userID, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockFileRepository)(nil).DownloadFile), ctx, userID, fileName)
}

// GetFileForName mocks base method.
func (m *MockFileRepository) GetFileForName(ctx context.Context, userID int, fileName string) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileForName", ctx, userID, fileName)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileForName indicates an expected call of GetFileForName.
func (mr *MockFileRepositoryMockRecorder) GetFileForName(ctx, userID, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileForName", reflect.TypeOf((*MockFileRepository)(nil).GetFileForName), ctx, userID, fileName)
}

// GetList mocks base method.
func (m *MockFileRepository) GetList(ctx context.Context, userID int) ([]model.FileAPI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, userID)
	ret0, _ := ret[0].([]model.FileAPI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockFileRepositoryMockRecorder) GetList(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockFileRepository)(nil).GetList), ctx, userID)
}
